CREATE TABLE `User_Info` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '회원정보 일련번호',
  `accountCode` char(9) NOT NULL COMMENT '계정코드',
  `accountID` varchar(255) NOT NULL COMMENT '회원 아이디',
  `accountPW` varchar(255) NOT NULL COMMENT '회원 패스워드',
  `cellNumber` int(11) NOT NULL COMMENT '휴대폰번호',
  `marketing` int(11) NOT NULL DEFAULT '0' COMMENT '마케팅 동의여부',
  `marketingAgreeTime` int(11) DEFAULT NULL COMMENT '마케팅 동의일시',
  `marketingReleaseTime` int(11) DEFAULT NULL COMMENT '마케팅 동의 해제일시',
  `isSuper` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT '운영자여부',
  `pwdFailCount` int(11) NOT NULL DEFAULT '0' COMMENT '비밀번호실패회수',
  `companyIdx` int(11) DEFAULT NULL COMMENT '회사정보 일련번호',
  `compoanyPosition` varchar(30) DEFAULT NULL COMMENT '직책',
  `companyPhoneNumber` int(11) DEFAULT NULL COMMENT '직통전화번호',
  `isCompanyAdmin` enum('Y','N') NOT NULL DEFAULT 'N' COMMENT '회사관리자여부',
  `permitService` int(11) DEFAULT NULL COMMENT '허용서비스',
  `writer` int(10) unsigned DEFAULT NULL COMMENT '작성자',
  `approveStatus` int(11) NOT NULL COMMENT '승인상태',
  `status` int(11) NOT NULL COMMENT '상태',
  `regUnixtime` int(11) NOT NULL DEFAULT '0' COMMENT '등록일',
  `updateUnixtime` int(11) NOT NULL DEFAULT '0' COMMENT '최종수정일',
  PRIMARY KEY (`idx`),
  KEY `accountID` (`accountID`),
  KEY `isSuper` (`isSuper`),
  KEY `account_fk_01` (`writer`),
  KEY `approveStatus` (`approveStatus`),
  KEY `accountCode` (`accountCode`),
  KEY `status` (`status`),
  CONSTRAINT `account_fk_01` FOREIGN KEY (`writer`) REFERENCES `Account_Info` (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='회원정보 테이블';

CREATE TABLE `Test_Info` (
  idx int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '일기 일련번호',
  contents text NOT NULL COMMENT '내용',
  regUnixtime int(11) NOT NULL COMMENT '등록일',
  updateUnixtime int(11) NOT NULL COMMENT '수정일',	
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='테스트 테이블';

CREATE TABLE `Board_Info` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '게시판 일련번호',
  `boardType` int(11) NOT NULL COMMENT '게시판 타입',
  `subject` varchar(255) NOT NULL COMMENT '제목',
  `contents` text NOT NULL COMMENT '내용',
  `categoryIdx1` int(11) DEFAULT '0' COMMENT '카테고리 일련번호(1차카테고리)',
  `categoryIdx2` int(11) DEFAULT '0' COMMENT '카테고리 일련번호(2차카테고리)',
  `categoryIdx3` int(11) DEFAULT '0' COMMENT '카테고리 일련번호(3차카테고리)',
  `boardDepth` int(11) NOT NULL DEFAULT '1' COMMENT '단계',
  `boardParent` int(10) unsigned DEFAULT NULL COMMENT '상위게시판번호',
  `writer` int(10) unsigned DEFAULT NULL COMMENT '작성자',
  `boardCode` char(9) NOT NULL COMMENT '게시판 코드',
  `languageCode` int(10) unsigned NOT NULL COMMENT '언어 일련번호',
  `permission` int(10) NOT NULL COMMENT '보기 권한',
  `viewCount` int(11) DEFAULT '0' COMMENT '조회수',
  `status` int(11) NOT NULL COMMENT '상태',
  `isOpen` ENUM('Y','N') NULL DEFAULT 'N' COMMENT '1대1문의 공개여부',
  `regUnixtime` int(11) NOT NULL COMMENT '등록일',
  `updateUnixtime` int(11) NOT NULL COMMENT '최종수정일',
  PRIMARY KEY (`idx`),
  KEY `boardType` (`boardType`),
  KEY `subject` (`subject`),
  KEY `status` (`status`),
  KEY `board_fk_01` (`boardParent`),
  CONSTRAINT `board_fk_01` FOREIGN KEY (`boardParent`) REFERENCES `Board_Info` (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='게시판 테이블';